import jsPDF from 'jspdf';

export async function generateSessionReport(sessionData) {
    const doc = new jsPDF();

    // Constants for layout
    const margin = 20;
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    let yPosition = margin;

    // Helper functions
    const addText = (text, fontSize = 12, fontStyle = 'normal', align = 'left') => {
        doc.setFontSize(fontSize);
        doc.setFont(undefined, fontStyle);

        if (align === 'center') {
            doc.text(text, pageWidth / 2, yPosition, { align: 'center' });
        } else {
            doc.text(text, margin, yPosition);
        }
        yPosition += fontSize * 0.4;
    };

    const addLine = () => {
        yPosition += 5;
        doc.line(margin, yPosition, pageWidth - margin, yPosition);
        yPosition += 10;
    };

    const checkPageBreak = (requiredSpace = 30) => {
        if (yPosition + requiredSpace > pageHeight - margin) {
            doc.addPage();
            yPosition = margin;
        }
    };

    // Header
    addText('Medical Examination Session Report', 24, 'bold', 'center');
    yPosition += 10;

    // Session info
    addText(`Student: ${sessionData.studentName}`, 14);
    addText(`Date: ${new Date(sessionData.sessionDate).toLocaleDateString()}`, 14);
    addText(`Session Duration: ${sessionData.duration || 'N/A'}`, 14);

    addLine();

    // Overall Performance
    addText('Overall Performance', 18, 'bold');
    yPosition += 5;
    addText(`Total Cases Completed: ${sessionData.totalCases}`, 14);
    addText(`Average Score: ${sessionData.averageScore}%`, 14);
    addText(`Grade: ${sessionData.grade}`, 14);

    addLine();

    // Individual Case Breakdown
    addText('Case-by-Case Breakdown', 18, 'bold');
    yPosition += 10;

    sessionData.cases.forEach((caseData, index) => {
        checkPageBreak(80);

        // Case header
        doc.setFillColor(240, 240, 240);
        doc.rect(margin, yPosition - 5, pageWidth - 2 * margin, 20, 'F');

        addText(`Case ${index + 1}: ${caseData.title || 'Untitled'}`, 16, 'bold');
        addText(`Score: ${caseData.score}% | Duration: ${caseData.duration || 'N/A'}`, 12);

        yPosition += 10;

        // Subsection scores
        if (caseData.subsections && caseData.subsections.length > 0) {
            addText('Subsection Performance:', 14, 'bold');
            yPosition += 5;

            caseData.subsections.forEach(subsection => {
                const scoreColor = subsection.score >= 80 ? [0, 128, 0] :
                    subsection.score >= 60 ? [255, 165, 0] : [255, 0, 0];

                doc.setTextColor(...scoreColor);
                addText(`  • ${subsection.name}: ${subsection.score}%`, 12);
                doc.setTextColor(0, 0, 0);

                if (subsection.feedback) {
                    doc.setFontSize(10);
                    doc.setTextColor(100, 100, 100);
                    const feedbackLines = doc.splitTextToSize(`    ${subsection.feedback}`, pageWidth - 2 * margin - 20);
                    feedbackLines.forEach(line => {
                        addText(line, 10);
                    });
                    doc.setTextColor(0, 0, 0);
                }
            });
        }

        // Case feedback
        if (caseData.feedback) {
            yPosition += 5;
            addText('Examiner Feedback:', 12, 'bold');
            const feedbackLines = doc.splitTextToSize(caseData.feedback, pageWidth - 2 * margin);
            feedbackLines.forEach(line => {
                addText(line, 11);
            });
        }

        yPosition += 15;
    });

    // Weak Areas Summary
    if (sessionData.weakAreas && sessionData.weakAreas.length > 0) {
        checkPageBreak(60);
        addLine();
        addText('Areas for Improvement', 18, 'bold');
        yPosition += 10;

        sessionData.weakAreas.forEach(area => {
            addText(`• ${area}`, 12);
        });
    }

    // Recommendations
    if (sessionData.recommendations && sessionData.recommendations.length > 0) {
        checkPageBreak(60);
        addLine();
        addText('Recommendations', 18, 'bold');
        yPosition += 10;

        sessionData.recommendations.forEach(rec => {
            const recLines = doc.splitTextToSize(`• ${rec}`, pageWidth - 2 * margin);
            recLines.forEach(line => {
                addText(line, 12);
            });
            yPosition += 5;
        });
    }

    // Footer
    checkPageBreak(40);
    addLine();
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by Medical Exam Preparation System', margin, pageHeight - 10);
    doc.text(`Page ${doc.internal.getNumberOfPages()}`, pageWidth - margin, pageHeight - 10, { align: 'right' });

    // Generate filename
    const fileName = `med-exam-report-${sessionData.studentName.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.pdf`;

    return {
        pdf: doc,
        fileName,
        download: () => doc.save(fileName),
        getBlob: () => doc.output('blob'),
        getDataUri: () => doc.output('datauristring')
    };
}

export function formatSessionDataForReport(sessionScores, cases, studentProfile) {
    // Calculate statistics
    const totalCases = cases.length;
    const averageScore = totalCases > 0
        ? Math.round(sessionScores.reduce((sum, s) => sum + s.score, 0) / totalCases)
        : 0;

    const grade = averageScore >= 90 ? 'A' :
        averageScore >= 80 ? 'B' :
            averageScore >= 70 ? 'C' :
                averageScore >= 60 ? 'D' : 'F';

    // Identify weak areas
    const weakAreas = [];
    const topicScores = {};

    sessionScores.forEach(score => {
        if (!topicScores[score.topic]) {
            topicScores[score.topic] = [];
        }
        topicScores[score.topic].push(score.score);
    });

    Object.entries(topicScores).forEach(([topic, scores]) => {
        const avgTopicScore = scores.reduce((a, b) => a + b, 0) / scores.length;
        if (avgTopicScore < 70) {
            weakAreas.push(`${topic} (avg: ${Math.round(avgTopicScore)}%)`);
        }
    });

    // Generate recommendations
    const recommendations = [];
    if (averageScore < 60) {
        recommendations.push('Review fundamental concepts across all systems');
        recommendations.push('Practice with easier cases before attempting complex scenarios');
    } else if (averageScore < 80) {
        recommendations.push('Focus on clinical reasoning and decision-making');
        recommendations.push('Practice time management during case discussions');
    }

    if (weakAreas.length > 0) {
        recommendations.push(`Prioritize revision of: ${weakAreas.slice(0, 3).join(', ')}`);
    }

    return {
        studentName: studentProfile?.name || 'Student',
        sessionDate: new Date().toISOString(),
        duration: calculateSessionDuration(sessionScores),
        totalCases,
        averageScore,
        grade,
        cases: cases.map((c, i) => ({
            id: c.id,
            title: c.title,
            score: sessionScores[i]?.score || 0,
            subsections: c.subsections || [],
            duration: c.duration,
            feedback: c.feedback
        })),
        weakAreas,
        recommendations
    };
}

function calculateSessionDuration(sessionScores) {
    if (sessionScores.length < 2) return 'N/A';

    const firstTime = new Date(sessionScores[0].timestamp);
    const lastTime = new Date(sessionScores[sessionScores.length - 1].timestamp);
    const durationMs = lastTime - firstTime;

    const minutes = Math.floor(durationMs / 60000);
    const hours = Math.floor(minutes / 60);

    if (hours > 0) {
        return `${hours}h ${minutes % 60}m`;
    }
    return `${minutes}m`;
} 
